### ISSUE TITLE
lucas oliveira-persona

### ISSUE THREAD

**Issue by WarlenAlves** [ICEI-PUC-Minas-PMV-ADS/iMobi#2]
![o-jovem-com-as-chaves-acaba-de-comprar-um-apartamento-novo](https://github.com/ICEI-PUC-Minas-PMV-ADS/iMobi/assets/101758971/af3feffa-e82d-40b0-bee9-3b523e81ef18)

**Comment by FerrGusttavo** [comment]
Persona finalizada
